services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
